---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: my-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: bertuz82/nginx:v0.1.2
          ports:
            - containerPort: 80
